<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Google.Protobuf" />
      <PackageReference Include="Grpc.AspNetCore" />
      <PackageReference Include="Grpc.Tools">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
      <PackageReference Include="Swashbuckle.AspNetCore" />
      <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Application\Gateway.Application.Contracts\Gateway.Application.Contracts.csproj" />
      <ProjectReference Include="..\Application\Gateway.Application\Gateway.Application.csproj" />
      <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\Presentation\Grpc\Grpc.csproj" />
    </ItemGroup>

</Project>
